### ISSUE TITLE
yarn on CI?

### ISSUE THREAD

**Issue by SethDavenport** [rangle/rangle-starter#189]
I'm a big fan of yarn: https://yarnpkg.com/

I don't think we should require people to use it, but it might be worth getting it to work on CI for reliability (yarn.lock) and build speed.

Should just be a matter of updating the circle.yaml as follows:

``` yaml
machine:
  node:
    version: 6
dependencies:
  pre:
    - npm install -g yarn@0.16.1
  override:
    - yarn install
test:
  pre:
    - yarn run clean
    - yarn run test:lint
  override:
    - yarn test
general:
  artifacts:
    - "./coverage"
```

And also doing `yarn install` locally and checking in the `yarn.lock` file.
